sudo: required
services:
  - docker

before_install:
  - docker build -t namewasntfound/docker-react -f Dockerfile.dev .

script:
  - docker run namewasntfound/docker-react npm run test -- --coverage
